/* Auto-generated by JumpCS CC65 Backend */
/* Bank 0 */

#include "methods.h"


/* Method ID 0: SpeedConverter.Program.RunTest(LSpeedConverter/Tests/SpeedConversionServiceTests;II)V */
/* Bank 0, offset 0x0000 */
#pragma codeseg(push, "BANK00")
void SpeedConverter_Program_RunTest(void)
{
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t s4 = 0;
    int32_t s5 = 0;

    /* IL_0000: ldarg.0 */
    /* IL_0001: ldarg.1 */
    /* IL_0002: ldarg.2 */
    /* IL_0003: callvirt */
    /* callvirt SpeedConverter.Tests.SpeedConversionServiceTests.ConvertToMilesPerHour_Input_Expected */
    s0 = call_banked(2); /* virtual ConvertToMilesPerHour_Input_Expected */
    /* IL_0008: stloc.0 */
    local_0 = s0;
    /* IL_0009: ldloca.s */
    /* IL_000B: ldc.i4.s */
    s1 = 17;
    /* IL_000D: ldc.i4.3 */
    s2 = 3;
    /* IL_000E: call */
    /* ERROR: Unsupported framework method: System.Runtime.CompilerServices.DefaultInterpolatedStringHandler::.ctor */
    /* Not in FrameworkMethodRegistry */
    /* IL_0013: ldloca.s */
    /* IL_0015: ldstr */
    /* ldstr 0x70000001 */
    s3 = (int32_t)0x70000001; /* string literal reference */
    /* IL_001A: call */
    /* ERROR: Unsupported framework method: System.Runtime.CompilerServices.DefaultInterpolatedStringHandler::AppendLiteral */
    /* Not in FrameworkMethodRegistry */
    /* IL_001F: ldloca.s */
    /* IL_0021: ldarg.1 */
    /* IL_0022: call */
    /* ERROR: Unsupported framework method: System.Runtime.CompilerServices.DefaultInterpolatedStringHandler::AppendFormatted */
    /* Not in FrameworkMethodRegistry */
    /* IL_0027: ldloca.s */
    /* IL_0029: ldstr */
    /* ldstr 0x7000000D */
    s4 = (int32_t)0x7000000D; /* string literal reference */
    /* IL_002E: call */
    /* ERROR: Unsupported framework method: System.Runtime.CompilerServices.DefaultInterpolatedStringHandler::AppendLiteral */
    /* Not in FrameworkMethodRegistry */
    /* IL_0033: ldloca.s */
    /* IL_0035: ldarg.2 */
    /* IL_0036: call */
    /* ERROR: Unsupported framework method: System.Runtime.CompilerServices.DefaultInterpolatedStringHandler::AppendFormatted */
    /* Not in FrameworkMethodRegistry */
    /* IL_003B: ldloca.s */
    /* IL_003D: ldstr */
    /* ldstr 0x70000021 */
    s5 = (int32_t)0x70000021; /* string literal reference */
    /* IL_0042: call */
    /* ERROR: Unsupported framework method: System.Runtime.CompilerServices.DefaultInterpolatedStringHandler::AppendLiteral */
    /* Not in FrameworkMethodRegistry */
    /* IL_0047: ldloca.s */
    /* IL_0049: ldloc.0 */
    /* IL_004A: call */
    /* ERROR: Unsupported framework method: System.Runtime.CompilerServices.DefaultInterpolatedStringHandler::AppendFormatted */
    /* Not in FrameworkMethodRegistry */
    /* IL_004F: ldloca.s */
    /* IL_0051: call */
    /* ERROR: Unsupported framework method: System.Runtime.CompilerServices.DefaultInterpolatedStringHandler::ToStringAndClear */
    /* Not in FrameworkMethodRegistry */
    /* IL_0056: call */
    /* Framework call: System.Console::WriteLine */
    /* IL_005B: ret */
    return s2;
}
#pragma codeseg(pop)

/* Method ID 1: SpeedConverter.Program.Main(LSystem/String[];)V */
/* Bank 0, offset 0x02E0 */
#pragma codeseg(push, "BANK00")
void SpeedConverter_Program_Main(void)
{
    int32_t local_0 = 0;
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t s4 = 0;
    int32_t s5 = 0;
    int32_t s6 = 0;

    /* IL_0000: newobj */
    /* TODO: newobj token 0x06000004 */
    s0 = 0; /* newobj placeholder */
    /* IL_0005: stloc.0 */
    local_0 = s0;
    /* IL_0006: ldloc.0 */
    /* IL_0007: ldc.i4.s */
    s1 = 10;
    /* IL_0009: ldc.i4.6 */
    s2 = 6;
    /* IL_000A: call */
    /* call SpeedConverter.Program.RunTest */
    call_banked(0); /* RunTest */
    /* IL_000F: ldloc.0 */
    /* IL_0010: ldc.i4.s */
    s3 = 11;
    /* IL_0012: ldc.i4.7 */
    s4 = 7;
    /* IL_0013: call */
    /* call SpeedConverter.Program.RunTest */
    call_banked(0); /* RunTest */
    /* IL_0018: ldloc.0 */
    /* IL_0019: ldc.i4.s */
    s5 = 20;
    /* IL_001B: ldc.i4.s */
    s6 = 12;
    /* IL_001D: call */
    /* call SpeedConverter.Program.RunTest */
    call_banked(0); /* RunTest */
    /* IL_0022: leave.s */
    goto IL_002E;
    /* IL_0024: ldloc.0 */
    /* IL_0025: brfalse.s */
    if (!local_0) goto IL_002D;
    /* IL_0027: ldloc.0 */
    /* IL_0028: callvirt */
    /* ERROR: Unsupported framework method: System.IDisposable::Dispose */
    /* Not in FrameworkMethodRegistry */
  IL_002D:
    /* IL_002D: endfinally */
    /* endfinally */
  IL_002E:
    /* IL_002E: ret */
    return;
}
#pragma codeseg(pop)

/* Method ID 2: SpeedConverter.Tests.SpeedConversionServiceTests.ConvertToMilesPerHour_Input_Expected(II)Z */
/* Bank 0, offset 0x0458 */
#pragma codeseg(push, "BANK00")
int32_t SpeedConverter_Tests_SpeedConversionServiceTests_ConvertToMilesPerHour_Input_Expected(void)
{
    int32_t local_0 = 0;
    int32_t s0 = 0;
    int32_t s1 = 0;

    /* IL_0000: ldarg.0 */
    /* IL_0001: ldfld */
    /* ldfld field 0x04000001 */
    s0 = arg_0; /* TODO: actual field access */
    /* IL_0006: ldarg.1 */
    /* IL_0007: callvirt */
    /* callvirt SpeedConverter.Code.SpeedConversionService.ConvertToMilesPerHour */
    s1 = call_banked(3); /* virtual ConvertToMilesPerHour */
    /* IL_000C: stloc.0 */
    local_0 = s1;
    /* IL_000D: ldarg.2 */
    /* IL_000E: ldloc.0 */
    /* IL_000F: nop */
    /* IL_0011: ret */
    return local_0;
    return 0;
}
#pragma codeseg(pop)

/* Method ID 3: SpeedConverter.Code.SpeedConversionService.ConvertToMilesPerHour(I)I */
/* Bank 0, offset 0x04E8 */
#pragma codeseg(push, "BANK00")
int32_t SpeedConverter_Code_SpeedConversionService_ConvertToMilesPerHour(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;

    /* IL_0000: ldarg.1 */
    /* IL_0001: conv.r8 */
    /* WARNING: double conversion not supported on 6502 */
    /* IL_0002: ldc.r8 */
    s0 = 0.62137; /* ldc.r8 */
    /* IL_000B: mul */
    s1 = arg_1 * s0;
    /* IL_000C: call */
    /* Framework call: System.Math::Round */
    /* Direct library call: __round */
    s2 = 0; /* TODO: return from __round */
    /* IL_0011: conv.i4 */
    s3 = (int32_t)s2;
    /* IL_0012: ret */
    return s3;
    return 0;
}
#pragma codeseg(pop)
