/* bank_00.c ? Generated by JumpCS CC65 Backend */
/* Atari XEGS Cartridge ? SMALL (32KB) */

#include "methods.h"


/* Method ID 0: SpeedConverter.Program.RunTest(LSpeedConverter/Tests/SpeedConversionServiceTests;II)V */
/* Bank 0, offset 0x0000 */
#pragma codeseg(push, "BANK00")
void SpeedConverter_Program_RunTest(void)
{
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t s4 = 0;
    int32_t s5 = 0;
    int32_t s6 = 0;
    int32_t s7 = 0;
    int32_t s8 = 0;
    int32_t s9 = 0;
    int32_t s10 = 0;
    int32_t s11 = 0;
    int32_t s12 = 0;
    int32_t s13 = 0;
    int32_t s14 = 0;
    int32_t s15 = 0;

    /* IL_0000: nop */
    /* IL_0001: ldarg.0 */
    /* IL_0002: ldarg.1 */
    /* TODO: Unimplemented opcode ldarg.1 */
    s0 = 0; /* placeholder */
    /* IL_0003: ldarg.2 */
    /* TODO: Unimplemented opcode ldarg.2 */
    s1 = 0; /* placeholder */
    /* IL_0004: callvirt */
    /* call SpeedConverter.Tests.SpeedConversionServiceTests.ConvertToMilesPerHour_Input_Expected */
    s2 = call_banked(2); /* SpeedConverter_Tests_SpeedConversionServiceTests_ConvertToMilesPerHour_Input_Expected */
    /* IL_0009: stloc.0 */
    local_0 = s2;
    /* IL_000A: ldloca.s */
    /* TODO: Unimplemented opcode ldloca.s */
    s3 = 0; /* placeholder */
    /* IL_000C: ldc.i4.s */
    s4 = 17;
    /* IL_000E: ldc.i4.3 */
    s5 = 3;
    /* IL_000F: call */
    /* TODO: framework call DefaultInterpolatedStringHandler::.ctor */
    /* IL_0014: ldloca.s */
    /* TODO: Unimplemented opcode ldloca.s */
    s6 = 0; /* placeholder */
    /* IL_0016: ldstr */
    /* TODO: Unimplemented opcode ldstr */
    /* IL_001B: call */
    /* TODO: framework call DefaultInterpolatedStringHandler::AppendLiteral */
    /* IL_0020: nop */
    /* IL_0021: ldloca.s */
    /* TODO: Unimplemented opcode ldloca.s */
    s7 = 0; /* placeholder */
    /* IL_0023: ldarg.1 */
    /* TODO: Unimplemented opcode ldarg.1 */
    s8 = 0; /* placeholder */
    /* IL_0024: call */
    /* TODO: framework call DefaultInterpolatedStringHandler::AppendFormatted */
    /* IL_0029: nop */
    /* IL_002A: ldloca.s */
    /* TODO: Unimplemented opcode ldloca.s */
    s9 = 0; /* placeholder */
    /* IL_002C: ldstr */
    /* TODO: Unimplemented opcode ldstr */
    /* IL_0031: call */
    /* TODO: framework call DefaultInterpolatedStringHandler::AppendLiteral */
    /* IL_0036: nop */
    /* IL_0037: ldloca.s */
    /* TODO: Unimplemented opcode ldloca.s */
    s10 = 0; /* placeholder */
    /* IL_0039: ldarg.2 */
    /* TODO: Unimplemented opcode ldarg.2 */
    s11 = 0; /* placeholder */
    /* IL_003A: call */
    /* TODO: framework call DefaultInterpolatedStringHandler::AppendFormatted */
    /* IL_003F: nop */
    /* IL_0040: ldloca.s */
    /* TODO: Unimplemented opcode ldloca.s */
    s12 = 0; /* placeholder */
    /* IL_0042: ldstr */
    /* TODO: Unimplemented opcode ldstr */
    /* IL_0047: call */
    /* TODO: framework call DefaultInterpolatedStringHandler::AppendLiteral */
    /* IL_004C: nop */
    /* IL_004D: ldloca.s */
    /* TODO: Unimplemented opcode ldloca.s */
    s13 = 0; /* placeholder */
    /* IL_004F: ldloc.0 */
    /* IL_0050: call */
    /* TODO: framework call DefaultInterpolatedStringHandler::AppendFormatted */
    /* IL_0055: nop */
    /* IL_0056: ldloca.s */
    /* TODO: Unimplemented opcode ldloca.s */
    s14 = 0; /* placeholder */
    /* IL_0058: call */
    /* TODO: framework call DefaultInterpolatedStringHandler::ToStringAndClear */
    s15 = 0; /* TODO: framework return */
    /* IL_005D: call */
    /* TODO: framework call Console::WriteLine */
    /* IL_0062: nop */
    /* IL_0063: ret */
    return s14;
}
#pragma codeseg(pop)

/* Method ID 1: SpeedConverter.Program.Main(LSystem/String[];)V */
/* Bank 0, offset 0x0320 */
#pragma codeseg(push, "BANK00")
void SpeedConverter_Program_Main(void)
{
    int32_t local_0 = 0;
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t s4 = 0;
    int32_t s5 = 0;
    int32_t s6 = 0;

    /* IL_0000: nop */
    /* IL_0001: newobj */
    /* TODO: newobj token 0x06000004 */
    s0 = 0; /* newobj placeholder */
    /* IL_0006: stloc.0 */
    local_0 = s0;
    /* IL_0007: nop */
    /* IL_0008: ldloc.0 */
    /* IL_0009: ldc.i4.s */
    s1 = 10;
    /* IL_000B: ldc.i4.6 */
    s2 = 6;
    /* IL_000C: call */
    /* call SpeedConverter.Program.RunTest */
    call_banked(0); /* SpeedConverter_Program_RunTest */
    /* IL_0011: nop */
    /* IL_0012: ldloc.0 */
    /* IL_0013: ldc.i4.s */
    s3 = 11;
    /* IL_0015: ldc.i4.7 */
    s4 = 7;
    /* IL_0016: call */
    /* call SpeedConverter.Program.RunTest */
    call_banked(0); /* SpeedConverter_Program_RunTest */
    /* IL_001B: nop */
    /* IL_001C: ldloc.0 */
    /* IL_001D: ldc.i4.s */
    s5 = 20;
    /* IL_001F: ldc.i4.s */
    s6 = 12;
    /* IL_0021: call */
    /* call SpeedConverter.Program.RunTest */
    call_banked(0); /* SpeedConverter_Program_RunTest */
    /* IL_0026: nop */
    /* IL_0027: nop */
    /* IL_0028: leave.s */
    goto IL_0035;
    /* IL_002A: ldloc.0 */
    /* IL_002B: brfalse.s */
    /* TODO: Unimplemented opcode brfalse.s */
    /* IL_002D: ldloc.0 */
    /* IL_002E: callvirt */
    /* TODO: framework call IDisposable::Dispose */
    /* IL_0033: nop */
  IL_0034:
    /* IL_0034: endfinally */
    /* TODO: Unimplemented opcode endfinally */
  IL_0035:
    /* IL_0035: ret */
    return local_0;
}
#pragma codeseg(pop)

/* Method ID 2: SpeedConverter.Tests.SpeedConversionServiceTests.ConvertToMilesPerHour_Input_Expected(II)Z */
/* Bank 0, offset 0x04D0 */
#pragma codeseg(push, "BANK00")
int32_t SpeedConverter_Tests_SpeedConversionServiceTests_ConvertToMilesPerHour_Input_Expected(void)
{
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;

    /* IL_0000: nop */
    /* IL_0001: ldarg.0 */
    /* IL_0002: ldfld */
    /* TODO: Unimplemented opcode ldfld */
    s0 = 0; /* placeholder */
    /* IL_0007: ldarg.1 */
    /* TODO: Unimplemented opcode ldarg.1 */
    s1 = 0; /* placeholder */
    /* IL_0008: callvirt */
    /* call SpeedConverter.Code.SpeedConversionService.ConvertToMilesPerHour */
    s2 = call_banked(3); /* SpeedConverter_Code_SpeedConversionService_ConvertToMilesPerHour */
    /* IL_000D: stloc.0 */
    local_0 = s2;
    /* IL_000E: ldarg.2 */
    /* TODO: Unimplemented opcode ldarg.2 */
    s3 = 0; /* placeholder */
    /* IL_000F: ldloc.0 */
    /* IL_0010: nop */
    /* IL_0012: stloc.1 */
    local_1 = local_0;
    /* IL_0013: br.s */
    goto IL_0015;
  IL_0015:
    /* IL_0015: ldloc.1 */
    /* IL_0016: ret */
    return local_1;
    return 0;
}
#pragma codeseg(pop)

/* Method ID 3: SpeedConverter.Code.SpeedConversionService.ConvertToMilesPerHour(I)I */
/* Bank 0, offset 0x0588 */
#pragma codeseg(push, "BANK00")
int32_t SpeedConverter_Code_SpeedConversionService_ConvertToMilesPerHour(void)
{
    int32_t local_0 = 0;
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t s4 = 0;

    /* IL_0000: nop */
    /* IL_0001: ldarg.1 */
    /* TODO: Unimplemented opcode ldarg.1 */
    s0 = 0; /* placeholder */
    /* IL_0002: conv.r8 */
    /* WARNING: double conversion not supported on 6502 */
    /* IL_0003: ldc.r8 */
    /* TODO: Unimplemented opcode ldc.r8 */
    s1 = 0; /* placeholder */
    /* IL_000C: mul */
    s2 = s0 * s1;
    /* IL_000D: call */
    /* TODO: framework call Math::Round */
    s3 = 0; /* TODO: framework return */
    /* IL_0012: conv.i4 */
    s4 = (int32_t)s3;
    /* IL_0013: stloc.0 */
    local_0 = s4;
    /* IL_0014: br.s */
    goto IL_0016;
  IL_0016:
    /* IL_0016: ldloc.0 */
    /* IL_0017: ret */
    return local_0;
    return 0;
}
#pragma codeseg(pop)
