/* kernel.c ? Fixed bank (last bank) */
/* Atari XEGS Cartridge ? Generated by JumpCS CC65 Backend */

/*
 * Memory Map:
 * $0000-$00FF  Zero Page (cc65 runtime + app vars)
 * $0100-$01FF  6502 Hardware Stack
 * $0200-$1FFF  Atari reserved (DOS)
 * $2000-$5FFF  Free RAM (globals, heap, software stack)
 * $6000-$7FFF  Atari reserved (display list, screen memory)
 * $8000-$9FFF  Switchable ROM bank (generated code)
 * $A000-$BFFF  Fixed ROM bank (this file)
 * $C000-$FFFF  Atari OS and H/W chips
 */

#include <atari.h>
#include <stdint.h>
#include "methods.h"

/* Bank switch register */
#define BANK_SELECT (*(volatile uint8_t*)0xD500)

/* Bank call stack for nested cross-bank calls */
#define BANK_STACK_SIZE 16
static uint8_t bank_stack[BANK_STACK_SIZE];
static uint8_t bank_sp = 0;
static uint8_t current_bank = 0;

void __fastcall__ switch_bank(uint8_t bank)
{
    current_bank = bank;
    BANK_SELECT = bank;
}

int32_t __fastcall__ call_banked(uint8_t method_id)
{
    int32_t result;
    uint8_t target_bank = method_bank_table[method_id];
    bank_stack[bank_sp++] = current_bank;
    switch_bank(target_bank);
    result = method_func_table[method_id]();
    switch_bank(bank_stack[--bank_sp]);
    return result;
}

/* Bank assignment table */
const uint8_t method_bank_table[NUM_METHODS] = {
    0,  /* 0: SpeedConverter.Program.RunTest(LSpeedConverter/Tests/SpeedConversionServiceTests;II)V */
    0,  /* 1: SpeedConverter.Program.Main(LSystem/String[];)V */
    0,  /* 2: SpeedConverter.Tests.SpeedConversionServiceTests.ConvertToMilesPerHour_Input_Expected(II)Z */
    0,  /* 3: SpeedConverter.Code.SpeedConversionService.ConvertToMilesPerHour(I)I */
};

/* Function pointer table */
int32_t (* const method_func_table[NUM_METHODS])(void) = {
    (int32_t (*)(void))SpeedConverter_Program_RunTest,  /* 0 */
    (int32_t (*)(void))SpeedConverter_Program_Main,  /* 1 */
    (int32_t (*)(void))SpeedConverter_Tests_SpeedConversionServiceTests_ConvertToMilesPerHour_Input_Expected,  /* 2 */
    (int32_t (*)(void))SpeedConverter_Code_SpeedConversionService_ConvertToMilesPerHour,  /* 3 */
};

/* Entry point */
void main(void)
{
    /* Initialize bank 0 */
    switch_bank(0);

    call_banked(1); /* SpeedConverter.Program.Main */

    /* Halt */
    for(;;);
}
