/* bank_00.c ? Generated by JumpCS CC65 Backend */
/* Atari XEGS Cartridge ? SMALL (32KB) */

#include "methods.h"


/* Method ID 0: JumpCS.TestMath.Program.AllIntegerMathTests()V */
/* Bank 0, offset 0x0000 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Program_AllIntegerMathTests(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;

/* IL_0000: nop */
/* IL_0001: call */
/* IL_0006: nop */
/* IL_0007: call */
/* IL_000C: nop */
/* IL_000D: call */
/* IL_0012: nop */
/* IL_0013: call */
/* IL_0018: nop */
/* IL_0019: call */
/* IL_001E: nop */
/* IL_001F: call */
/* IL_0024: nop */
/* IL_0025: call */
/* IL_002A: nop */
/* IL_002B: call */
/* IL_0030: nop */
/* IL_0031: call */
/* IL_0036: nop */
/* IL_0037: call */
/* IL_003C: nop */
/* IL_003D: call */
/* IL_0042: nop */
/* IL_0043: call */
/* IL_0048: nop */
/* IL_0049: call */
/* IL_004E: nop */
/* IL_004F: call */
/* IL_0054: nop */
/* IL_0055: call */
/* IL_005A: nop */
/* IL_005B: call */
/* IL_0060: nop */
/* IL_0061: call */
/* IL_0066: nop */
/* IL_0067: call */
/* IL_006C: nop */
/* IL_006D: call */
/* IL_0072: nop */
/* IL_0073: call */
/* IL_0078: nop */
/* IL_0079: call */
/* IL_007E: nop */
/* IL_007F: call */
/* IL_0084: nop */
/* IL_0085: call */
/* IL_008A: nop */
/* IL_008B: call */
/* IL_0090: nop */
/* IL_0091: call */
/* IL_0096: nop */
/* IL_0097: call */
/* IL_009C: nop */
/* IL_009D: ret */
}
#pragma codeseg(pop)

/* Method ID 1: JumpCS.TestMath.Program.Main()V */
/* Bank 0, offset 0x04F0 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Program_Main(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t s4 = 0;
    int32_t s5 = 0;
    int32_t s6 = 0;
    int32_t s7 = 0;
    int32_t s8 = 0;
    int32_t s9 = 0;
    int32_t s10 = 0;
    int32_t s11 = 0;
    int32_t s12 = 0;
    int32_t s13 = 0;
    int32_t s14 = 0;
    int32_t s15 = 0;

/* IL_0000: nop */
/* IL_0001: call */
/* IL_0006: nop */
/* IL_0007: ret */
}
#pragma codeseg(pop)

/* Method ID 2: JumpCS.TestMath.Tests.IntegerMathTests.Addition_PositiveNumbers()V */
/* Bank 0, offset 0x0530 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Addition_PositiveNumbers(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.s */
/* IL_0006: stloc.1 */
/* IL_0007: ldloc.0 */
/* IL_0008: ldloc.1 */
/* IL_0009: add */
/* IL_000A: stloc.2 */
/* IL_000B: ldc.i4.s */
/* IL_000D: box */
/* IL_0012: ldloc.2 */
/* IL_0013: box */
/* IL_0018: call */
/* IL_001D: stloc.3 */
/* IL_001E: ret */
}
#pragma codeseg(pop)

/* Method ID 3: JumpCS.TestMath.Tests.IntegerMathTests.Addition_NegativeNumbers()V */
/* Bank 0, offset 0x0628 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Addition_NegativeNumbers(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.s */
/* IL_0006: stloc.1 */
/* IL_0007: ldloc.0 */
/* IL_0008: ldloc.1 */
/* IL_0009: add */
/* IL_000A: stloc.2 */
/* IL_000B: ldc.i4.s */
/* IL_000D: box */
/* IL_0012: ldloc.2 */
/* IL_0013: box */
/* IL_0018: call */
/* IL_001D: stloc.3 */
/* IL_001E: ret */
}
#pragma codeseg(pop)

/* Method ID 4: JumpCS.TestMath.Tests.IntegerMathTests.Addition_MixedSigns()V */
/* Bank 0, offset 0x0720 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Addition_MixedSigns(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.s */
/* IL_0006: stloc.1 */
/* IL_0007: ldloc.0 */
/* IL_0008: ldloc.1 */
/* IL_0009: add */
/* IL_000A: stloc.2 */
/* IL_000B: ldc.i4.s */
/* IL_000D: box */
/* IL_0012: ldloc.2 */
/* IL_0013: box */
/* IL_0018: call */
/* IL_001D: stloc.3 */
/* IL_001E: ret */
}
#pragma codeseg(pop)

/* Method ID 5: JumpCS.TestMath.Tests.IntegerMathTests.Addition_Overflow()V */
/* Bank 0, offset 0x0818 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Addition_Overflow(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4 */
/* IL_0006: stloc.0 */
/* IL_0007: ldc.i4.1 */
/* IL_0008: stloc.1 */
/* IL_0009: ldloc.0 */
/* IL_000A: ldloc.1 */
/* IL_000B: add */
/* IL_000C: stloc.2 */
/* IL_000D: ldc.i4 */
/* IL_0012: box */
/* IL_0017: ldloc.2 */
/* IL_0018: box */
/* IL_001D: call */
/* IL_0022: stloc.3 */
/* IL_0023: ret */
}
#pragma codeseg(pop)

/* Method ID 6: JumpCS.TestMath.Tests.IntegerMathTests.Subtraction_PositiveNumbers()V */
/* Bank 0, offset 0x0938 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Subtraction_PositiveNumbers(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.s */
/* IL_0006: stloc.1 */
/* IL_0007: ldloc.0 */
/* IL_0008: ldloc.1 */
/* IL_0009: sub */
/* IL_000A: stloc.2 */
/* IL_000B: ldc.i4.s */
/* IL_000D: box */
/* IL_0012: ldloc.2 */
/* IL_0013: box */
/* IL_0018: call */
/* IL_001D: stloc.3 */
/* IL_001E: ret */
}
#pragma codeseg(pop)

/* Method ID 7: JumpCS.TestMath.Tests.IntegerMathTests.Subtraction_NegativeResult()V */
/* Bank 0, offset 0x0A30 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Subtraction_NegativeResult(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.s */
/* IL_0006: stloc.1 */
/* IL_0007: ldloc.0 */
/* IL_0008: ldloc.1 */
/* IL_0009: sub */
/* IL_000A: stloc.2 */
/* IL_000B: ldc.i4.s */
/* IL_000D: box */
/* IL_0012: ldloc.2 */
/* IL_0013: box */
/* IL_0018: call */
/* IL_001D: stloc.3 */
/* IL_001E: ret */
}
#pragma codeseg(pop)

/* Method ID 8: JumpCS.TestMath.Tests.IntegerMathTests.Subtraction_NegativeNumbers()V */
/* Bank 0, offset 0x0B28 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Subtraction_NegativeNumbers(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.s */
/* IL_0006: stloc.1 */
/* IL_0007: ldloc.0 */
/* IL_0008: ldloc.1 */
/* IL_0009: sub */
/* IL_000A: stloc.2 */
/* IL_000B: ldc.i4.s */
/* IL_000D: box */
/* IL_0012: ldloc.2 */
/* IL_0013: box */
/* IL_0018: call */
/* IL_001D: stloc.3 */
/* IL_001E: ret */
}
#pragma codeseg(pop)

/* Method ID 9: JumpCS.TestMath.Tests.IntegerMathTests.Multiplication_PositiveNumbers()V */
/* Bank 0, offset 0x0C20 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Multiplication_PositiveNumbers(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.7 */
/* IL_0005: stloc.1 */
/* IL_0006: ldloc.0 */
/* IL_0007: ldloc.1 */
/* IL_0008: mul */
/* IL_0009: stloc.2 */
/* IL_000A: ldc.i4.s */
/* IL_000C: box */
/* IL_0011: ldloc.2 */
/* IL_0012: box */
/* IL_0017: call */
/* IL_001C: stloc.3 */
/* IL_001D: ret */
}
#pragma codeseg(pop)

/* Method ID 10: JumpCS.TestMath.Tests.IntegerMathTests.Multiplication_ByZero()V */
/* Bank 0, offset 0x0D10 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Multiplication_ByZero(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.0 */
/* IL_0005: stloc.1 */
/* IL_0006: ldloc.0 */
/* IL_0007: ldloc.1 */
/* IL_0008: mul */
/* IL_0009: stloc.2 */
/* IL_000A: ldc.i4.0 */
/* IL_000B: box */
/* IL_0010: ldloc.2 */
/* IL_0011: box */
/* IL_0016: call */
/* IL_001B: stloc.3 */
/* IL_001C: ret */
}
#pragma codeseg(pop)

/* Method ID 11: JumpCS.TestMath.Tests.IntegerMathTests.Multiplication_NegativeNumbers()V */
/* Bank 0, offset 0x0DF8 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Multiplication_NegativeNumbers(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.s */
/* IL_0006: stloc.1 */
/* IL_0007: ldloc.0 */
/* IL_0008: ldloc.1 */
/* IL_0009: mul */
/* IL_000A: stloc.2 */
/* IL_000B: ldc.i4.s */
/* IL_000D: box */
/* IL_0012: ldloc.2 */
/* IL_0013: box */
/* IL_0018: call */
/* IL_001D: stloc.3 */
/* IL_001E: ret */
}
#pragma codeseg(pop)

/* Method ID 12: JumpCS.TestMath.Tests.IntegerMathTests.Multiplication_MixedSigns()V */
/* Bank 0, offset 0x0EF0 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Multiplication_MixedSigns(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.s */
/* IL_0006: stloc.1 */
/* IL_0007: ldloc.0 */
/* IL_0008: ldloc.1 */
/* IL_0009: mul */
/* IL_000A: stloc.2 */
/* IL_000B: ldc.i4.s */
/* IL_000D: box */
/* IL_0012: ldloc.2 */
/* IL_0013: box */
/* IL_0018: call */
/* IL_001D: stloc.3 */
/* IL_001E: ret */
}
#pragma codeseg(pop)

/* Method ID 13: JumpCS.TestMath.Tests.IntegerMathTests.Division_PositiveNumbers()V */
/* Bank 0, offset 0x0FE8 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Division_PositiveNumbers(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.7 */
/* IL_0005: stloc.1 */
/* IL_0006: ldloc.0 */
/* IL_0007: ldloc.1 */
/* IL_0008: div */
/* IL_0009: stloc.2 */
/* IL_000A: ldc.i4.s */
/* IL_000C: box */
/* IL_0011: ldloc.2 */
/* IL_0012: box */
/* IL_0017: call */
/* IL_001C: stloc.3 */
/* IL_001D: ret */
}
#pragma codeseg(pop)

/* Method ID 14: JumpCS.TestMath.Tests.IntegerMathTests.Division_WithRemainder()V */
/* Bank 0, offset 0x10D8 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Division_WithRemainder(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.7 */
/* IL_0005: stloc.1 */
/* IL_0006: ldloc.0 */
/* IL_0007: ldloc.1 */
/* IL_0008: div */
/* IL_0009: stloc.2 */
/* IL_000A: ldc.i4.s */
/* IL_000C: box */
/* IL_0011: ldloc.2 */
/* IL_0012: box */
/* IL_0017: call */
/* IL_001C: stloc.3 */
/* IL_001D: ret */
}
#pragma codeseg(pop)

/* Method ID 15: JumpCS.TestMath.Tests.IntegerMathTests.Division_NegativeNumbers()V */
/* Bank 0, offset 0x11C8 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Division_NegativeNumbers(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.s */
/* IL_0006: stloc.1 */
/* IL_0007: ldloc.0 */
/* IL_0008: ldloc.1 */
/* IL_0009: div */
/* IL_000A: stloc.2 */
/* IL_000B: ldc.i4.s */
/* IL_000D: box */
/* IL_0012: ldloc.2 */
/* IL_0013: box */
/* IL_0018: call */
/* IL_001D: stloc.3 */
/* IL_001E: ret */
}
#pragma codeseg(pop)

/* Method ID 16: JumpCS.TestMath.Tests.IntegerMathTests.Division_MixedSigns()V */
/* Bank 0, offset 0x12C0 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Division_MixedSigns(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.s */
/* IL_0006: stloc.1 */
/* IL_0007: ldloc.0 */
/* IL_0008: ldloc.1 */
/* IL_0009: div */
/* IL_000A: stloc.2 */
/* IL_000B: ldc.i4.s */
/* IL_000D: box */
/* IL_0012: ldloc.2 */
/* IL_0013: box */
/* IL_0018: call */
/* IL_001D: stloc.3 */
/* IL_001E: ret */
}
#pragma codeseg(pop)

/* Method ID 17: JumpCS.TestMath.Tests.IntegerMathTests.Remainder_PositiveNumbers()V */
/* Bank 0, offset 0x13B8 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Remainder_PositiveNumbers(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.7 */
/* IL_0005: stloc.1 */
/* IL_0006: ldloc.0 */
/* IL_0007: ldloc.1 */
/* IL_0008: rem */
/* IL_0009: stloc.2 */
/* IL_000A: ldc.i4.1 */
/* IL_000B: box */
/* IL_0010: ldloc.2 */
/* IL_0011: box */
/* IL_0016: call */
/* IL_001B: stloc.3 */
/* IL_001C: ret */
}
#pragma codeseg(pop)

/* Method ID 18: JumpCS.TestMath.Tests.IntegerMathTests.Remainder_NegativeNumbers()V */
/* Bank 0, offset 0x14A0 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_Remainder_NegativeNumbers(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.7 */
/* IL_0005: stloc.1 */
/* IL_0006: ldloc.0 */
/* IL_0007: ldloc.1 */
/* IL_0008: rem */
/* IL_0009: stloc.2 */
/* IL_000A: ldc.i4.m1 */
/* IL_000B: box */
/* IL_0010: ldloc.2 */
/* IL_0011: box */
/* IL_0016: call */
/* IL_001B: stloc.3 */
/* IL_001C: ret */
}
#pragma codeseg(pop)

/* Method ID 19: JumpCS.TestMath.Tests.IntegerMathTests.BitwiseAnd()V */
/* Bank 0, offset 0x1588 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_BitwiseAnd(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4 */
/* IL_0006: stloc.0 */
/* IL_0007: ldc.i4 */
/* IL_000C: stloc.1 */
/* IL_000D: ldloc.0 */
/* IL_000E: ldloc.1 */
/* IL_000F: and */
/* IL_0010: stloc.2 */
/* IL_0011: ldc.i4 */
/* IL_0016: box */
/* IL_001B: ldloc.2 */
/* IL_001C: box */
/* IL_0021: call */
/* IL_0026: stloc.3 */
/* IL_0027: ret */
}
#pragma codeseg(pop)

/* Method ID 20: JumpCS.TestMath.Tests.IntegerMathTests.BitwiseOr()V */
/* Bank 0, offset 0x16C8 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_BitwiseOr(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4 */
/* IL_0006: stloc.0 */
/* IL_0007: ldc.i4 */
/* IL_000C: stloc.1 */
/* IL_000D: ldloc.0 */
/* IL_000E: ldloc.1 */
/* IL_000F: or */
/* IL_0010: stloc.2 */
/* IL_0011: ldc.i4 */
/* IL_0016: box */
/* IL_001B: ldloc.2 */
/* IL_001C: box */
/* IL_0021: call */
/* IL_0026: stloc.3 */
/* IL_0027: ret */
}
#pragma codeseg(pop)

/* Method ID 21: JumpCS.TestMath.Tests.IntegerMathTests.BitwiseXor()V */
/* Bank 0, offset 0x1808 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_BitwiseXor(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4 */
/* IL_0006: stloc.0 */
/* IL_0007: ldc.i4 */
/* IL_000C: stloc.1 */
/* IL_000D: ldloc.0 */
/* IL_000E: ldloc.1 */
/* IL_000F: xor */
/* IL_0010: stloc.2 */
/* IL_0011: ldc.i4.s */
/* IL_0013: box */
/* IL_0018: ldloc.2 */
/* IL_0019: box */
/* IL_001E: call */
/* IL_0023: stloc.3 */
/* IL_0024: ret */
}
#pragma codeseg(pop)

/* Method ID 22: JumpCS.TestMath.Tests.IntegerMathTests.LeftShift()V */
/* Bank 0, offset 0x1930 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_LeftShift(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.1 */
/* IL_0002: stloc.0 */
/* IL_0003: ldloc.0 */
/* IL_0004: ldc.i4.4 */
/* IL_0005: shl */
/* IL_0006: stloc.1 */
/* IL_0007: ldc.i4.s */
/* IL_0009: box */
/* IL_000E: ldloc.1 */
/* IL_000F: box */
/* IL_0014: call */
/* IL_0019: stloc.2 */
/* IL_001A: ret */
}
#pragma codeseg(pop)

/* Method ID 23: JumpCS.TestMath.Tests.IntegerMathTests.RightShift()V */
/* Bank 0, offset 0x1A08 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_RightShift(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldloc.0 */
/* IL_0005: ldc.i4.4 */
/* IL_0006: shr */
/* IL_0007: stloc.1 */
/* IL_0008: ldc.i4.1 */
/* IL_0009: box */
/* IL_000E: ldloc.1 */
/* IL_000F: box */
/* IL_0014: call */
/* IL_0019: stloc.2 */
/* IL_001A: ret */
}
#pragma codeseg(pop)

/* Method ID 24: JumpCS.TestMath.Tests.IntegerMathTests.UnaryMinus()V */
/* Bank 0, offset 0x1AE0 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_UnaryMinus(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldloc.0 */
/* IL_0005: neg */
/* IL_0006: stloc.1 */
/* IL_0007: ldc.i4.s */
/* IL_0009: box */
/* IL_000E: ldloc.1 */
/* IL_000F: box */
/* IL_0014: call */
/* IL_0019: stloc.2 */
/* IL_001A: ret */
}
#pragma codeseg(pop)

/* Method ID 25: JumpCS.TestMath.Tests.IntegerMathTests.ChainedOperations()V */
/* Bank 0, offset 0x1BB8 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_ChainedOperations(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;
    int32_t local_4 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.s */
/* IL_0006: stloc.1 */
/* IL_0007: ldc.i4.3 */
/* IL_0008: stloc.2 */
/* IL_0009: ldloc.0 */
/* IL_000A: ldloc.1 */
/* IL_000B: add */
/* IL_000C: ldloc.2 */
/* IL_000D: mul */
/* IL_000E: ldc.i4.5 */
/* IL_000F: sub */
/* IL_0010: stloc.3 */
/* IL_0011: ldc.i4.s */
/* IL_0013: box */
/* IL_0018: ldloc.3 */
/* IL_0019: box */
/* IL_001E: call */
/* IL_0023: stloc.s */
/* IL_0025: ret */
}
#pragma codeseg(pop)

/* Method ID 26: JumpCS.TestMath.Tests.IntegerMathTests.DivideByZeroThrows()V */
/* Bank 0, offset 0x1CE8 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_DivideByZeroThrows(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.0 */
/* IL_0005: stloc.1 */
/* IL_0006: ldc.i4.1 */
/* IL_0007: stloc.2 */
/* IL_0008: nop */
/* IL_0009: ldloc.0 */
/* IL_000A: ldloc.1 */
/* IL_000B: div */
/* IL_000C: stloc.3 */
/* IL_000D: nop */
/* IL_000E: leave.s */
/* IL_0010: pop */
/* IL_0011: nop */
/* IL_0012: ldc.i4.0 */
/* IL_0013: stloc.2 */
/* IL_0014: nop */
/* IL_0015: leave.s */
/* IL_0017: ret */
}
#pragma codeseg(pop)

/* Method ID 27: JumpCS.TestMath.Tests.IntegerMathTests.ModuloByZeroThrows()V */
/* Bank 0, offset 0x1DA8 */
#pragma codeseg(push, "BANK00")
void JumpCS_TestMath_Tests_IntegerMathTests_ModuloByZeroThrows(void)
{
    int32_t s0 = 0;
    int32_t s1 = 0;
    int32_t s2 = 0;
    int32_t s3 = 0;
    int32_t local_0 = 0;
    int32_t local_1 = 0;
    int32_t local_2 = 0;
    int32_t local_3 = 0;

/* IL_0000: nop */
/* IL_0001: ldc.i4.s */
/* IL_0003: stloc.0 */
/* IL_0004: ldc.i4.0 */
/* IL_0005: stloc.1 */
/* IL_0006: ldc.i4.1 */
/* IL_0007: stloc.2 */
/* IL_0008: nop */
/* IL_0009: ldloc.0 */
/* IL_000A: ldloc.1 */
/* IL_000B: rem */
/* IL_000C: stloc.3 */
/* IL_000D: nop */
/* IL_000E: leave.s */
/* IL_0010: pop */
/* IL_0011: nop */
/* IL_0012: ldc.i4.0 */
/* IL_0013: stloc.2 */
/* IL_0014: nop */
/* IL_0015: leave.s */
/* IL_0017: ret */
}
#pragma codeseg(pop)
