/* kernel.c ? Fixed bank (last bank) */
/* Atari XEGS Cartridge ? Generated by JumpCS CC65 Backend */

/*
 * Memory Map:
 * $0000-$00FF  Zero Page (cc65 runtime + app vars)
 * $0100-$01FF  6502 Hardware Stack
 * $0200-$1FFF  Atari reserved (DOS)
 * $2000-$5FFF  Free RAM (globals, heap, software stack)
 * $6000-$7FFF  Atari reserved (display list, screen memory)
 * $8000-$9FFF  Switchable ROM bank (generated code)
 * $A000-$BFFF  Fixed ROM bank (this file)
 * $C000-$FFFF  Atari OS and H/W chips
 */

#include <atari.h>
#include <stdint.h>
#include "methods.h"

/* Bank switch register */
#define BANK_SELECT (*(volatile uint8_t*)0xD500)

/* Bank call stack for nested cross-bank calls */
#define BANK_STACK_SIZE 16
static uint8_t bank_stack[BANK_STACK_SIZE];
static uint8_t bank_sp = 0;
static uint8_t current_bank = 0;

void __fastcall__ switch_bank(uint8_t bank)
{
    current_bank = bank;
    BANK_SELECT = bank;
}

int32_t __fastcall__ call_banked(uint8_t method_id)
{
    int32_t result;
    uint8_t target_bank = method_bank_table[method_id];
    bank_stack[bank_sp++] = current_bank;
    switch_bank(target_bank);
    result = method_func_table[method_id]();
    switch_bank(bank_stack[--bank_sp]);
    return result;
}

/* Bank assignment table */
const uint8_t method_bank_table[NUM_METHODS] = {
    0,  /* 0: JumpCS.TestMath.Program.AllIntegerMathTests()V */
    0,  /* 1: JumpCS.TestMath.Program.Main()V */
    0,  /* 2: JumpCS.TestMath.Tests.IntegerMathTests.Addition_PositiveNumbers()V */
    0,  /* 3: JumpCS.TestMath.Tests.IntegerMathTests.Addition_NegativeNumbers()V */
    0,  /* 4: JumpCS.TestMath.Tests.IntegerMathTests.Addition_MixedSigns()V */
    0,  /* 5: JumpCS.TestMath.Tests.IntegerMathTests.Addition_Overflow()V */
    0,  /* 6: JumpCS.TestMath.Tests.IntegerMathTests.Subtraction_PositiveNumbers()V */
    0,  /* 7: JumpCS.TestMath.Tests.IntegerMathTests.Subtraction_NegativeResult()V */
    0,  /* 8: JumpCS.TestMath.Tests.IntegerMathTests.Subtraction_NegativeNumbers()V */
    0,  /* 9: JumpCS.TestMath.Tests.IntegerMathTests.Multiplication_PositiveNumbers()V */
    0,  /* 10: JumpCS.TestMath.Tests.IntegerMathTests.Multiplication_ByZero()V */
    0,  /* 11: JumpCS.TestMath.Tests.IntegerMathTests.Multiplication_NegativeNumbers()V */
    0,  /* 12: JumpCS.TestMath.Tests.IntegerMathTests.Multiplication_MixedSigns()V */
    0,  /* 13: JumpCS.TestMath.Tests.IntegerMathTests.Division_PositiveNumbers()V */
    0,  /* 14: JumpCS.TestMath.Tests.IntegerMathTests.Division_WithRemainder()V */
    0,  /* 15: JumpCS.TestMath.Tests.IntegerMathTests.Division_NegativeNumbers()V */
    0,  /* 16: JumpCS.TestMath.Tests.IntegerMathTests.Division_MixedSigns()V */
    0,  /* 17: JumpCS.TestMath.Tests.IntegerMathTests.Remainder_PositiveNumbers()V */
    0,  /* 18: JumpCS.TestMath.Tests.IntegerMathTests.Remainder_NegativeNumbers()V */
    0,  /* 19: JumpCS.TestMath.Tests.IntegerMathTests.BitwiseAnd()V */
    0,  /* 20: JumpCS.TestMath.Tests.IntegerMathTests.BitwiseOr()V */
    0,  /* 21: JumpCS.TestMath.Tests.IntegerMathTests.BitwiseXor()V */
    0,  /* 22: JumpCS.TestMath.Tests.IntegerMathTests.LeftShift()V */
    0,  /* 23: JumpCS.TestMath.Tests.IntegerMathTests.RightShift()V */
    0,  /* 24: JumpCS.TestMath.Tests.IntegerMathTests.UnaryMinus()V */
    0,  /* 25: JumpCS.TestMath.Tests.IntegerMathTests.ChainedOperations()V */
    0,  /* 26: JumpCS.TestMath.Tests.IntegerMathTests.DivideByZeroThrows()V */
    0,  /* 27: JumpCS.TestMath.Tests.IntegerMathTests.ModuloByZeroThrows()V */
};

/* Function pointer table */
int32_t (* const method_func_table[NUM_METHODS])(void) = {
    (int32_t (*)(void))JumpCS_TestMath_Program_AllIntegerMathTests,  /* 0 */
    (int32_t (*)(void))JumpCS_TestMath_Program_Main,  /* 1 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Addition_PositiveNumbers,  /* 2 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Addition_NegativeNumbers,  /* 3 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Addition_MixedSigns,  /* 4 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Addition_Overflow,  /* 5 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Subtraction_PositiveNumbers,  /* 6 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Subtraction_NegativeResult,  /* 7 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Subtraction_NegativeNumbers,  /* 8 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Multiplication_PositiveNumbers,  /* 9 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Multiplication_ByZero,  /* 10 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Multiplication_NegativeNumbers,  /* 11 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Multiplication_MixedSigns,  /* 12 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Division_PositiveNumbers,  /* 13 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Division_WithRemainder,  /* 14 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Division_NegativeNumbers,  /* 15 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Division_MixedSigns,  /* 16 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Remainder_PositiveNumbers,  /* 17 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_Remainder_NegativeNumbers,  /* 18 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_BitwiseAnd,  /* 19 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_BitwiseOr,  /* 20 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_BitwiseXor,  /* 21 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_LeftShift,  /* 22 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_RightShift,  /* 23 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_UnaryMinus,  /* 24 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_ChainedOperations,  /* 25 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_DivideByZeroThrows,  /* 26 */
    (int32_t (*)(void))JumpCS_TestMath_Tests_IntegerMathTests_ModuloByZeroThrows,  /* 27 */
};

/* Entry point */
void main(void)
{
    /* Initialize bank 0 */
    switch_bank(0);

    call_banked(1); /* JumpCS.TestMath.Program.Main */

    /* Halt */
    for(;;);
}
