using JumpCS.Backend.Base;
using JumpCS.Backend.Interfaces;
using JumpCS.Core;
using System.Text;

namespace JumpCS.Backend.CC65;

/// <summary>CC65 C code backend targeting Atari XEGS cartridge</summary>
public class CC65BackEnd : BackEndBase, IBackEnd
{
    private readonly MemoryModel _model;
    private CC65MethodBank _methodBank;

    public CC65BackEnd(string outputBaseName, MemoryModel model) : base(outputBaseName)
    {
        _model = model;
        _methodBank = new CC65MethodBank(model);
    }

    public override void UpdateAll()
    {
        _methodCache.Clear();
        _methodBank = new CC65MethodBank(_model);

        AnalyzeMsilDependencies();

        foreach (var cls in ClassMetadata.AllClasses.Where(c => c.IsNeeded))
        {
            foreach (var method in cls.Methods.Where(m => m.IsNeeded))
            {
                int size = CC65MethodBank.EstimateMethodSize(method);
                _methodBank.AssignMethod(cls, method, size);
            }
        }
    }

    public override void Generate()
    {
        string outputDir = $"{OutputBaseName}_cc65";
        Directory.CreateDirectory(outputDir);

        Console.WriteLine($"Generating CC65 output for Atari XEGS ({CC65CartModel.ModelName(_model)}): {outputDir}/");
        Console.WriteLine($"  Banks used: {_methodBank.BanksUsed} of {CC65CartModel.SwitchableBanks(_model)} switchable + 1 fixed");

        // Generate bank source files
        for (int bank = 0; bank < _methodBank.BanksUsed; bank++)
        {
            string bankPath = Path.Combine(outputDir, $"bank_{bank:D2}.c");
            using var writer = new StreamWriter(bankPath, false, Encoding.ASCII);
            WriteBankFile(writer, bank);
            AddGeneratedFile(bankPath);
        }

        // Generate fixed bank (kernel/dispatcher)
        string kernelPath = Path.Combine(outputDir, "kernel.c");
        using (var writer = new StreamWriter(kernelPath, false, Encoding.ASCII))
        {
            WriteKernelFile(writer);
        }
        AddGeneratedFile(kernelPath);

        // Generate shared header
        string headerPath = Path.Combine(outputDir, "methods.h");
        using (var writer = new StreamWriter(headerPath, false, Encoding.ASCII))
        {
            WriteMethodsHeader(writer);
        }
        AddGeneratedFile(headerPath);

        // Generate linker config
        string cfgPath = Path.Combine(outputDir, "xegs.cfg");
        using (var writer = new StreamWriter(cfgPath, false, Encoding.ASCII))
        {
            WriteLinkerConfig(writer);
        }
        AddGeneratedFile(cfgPath);

        // Generate Makefile
        string makePath = Path.Combine(outputDir, "Makefile");
        using (var writer = new StreamWriter(makePath, false, Encoding.ASCII))
        {
            WriteMakefile(writer);
        }
        AddGeneratedFile(makePath);
    }

    // --- Bank source files ---

    private void WriteBankFile(StreamWriter writer, int bank)
    {
        writer.WriteLine($"/* bank_{bank:D2}.c — Generated by JumpCS CC65 Backend */");
        writer.WriteLine($"/* Atari XEGS Cartridge — {CC65CartModel.ModelName(_model)} */");
        writer.WriteLine();
        writer.WriteLine("#include \"methods.h\"");
        writer.WriteLine();

        foreach (var cls in ClassMetadata.AllClasses.Where(c => c.IsNeeded))
        {
            foreach (var method in cls.Methods.Where(m => m.IsNeeded))
            {
                string key = CC65MethodBank.GetMethodKey(cls, method);
                if (_methodBank.Assignments.TryGetValue(key, out var assign) && assign.Bank == bank)
                {
                    WriteMethodToC(writer, cls, method, assign);
                }
            }
        }
    }

    private void WriteMethodToC(StreamWriter writer, ClassMetadata cls, MethodMetadata method, BankAssignment assign)
    {
        string funcName = GetCFunctionName(cls, method);
        string returnType = CC65TypeMapper.ReturnTypeFromSignature(method.Signature);

        writer.WriteLine();
        writer.WriteLine($"/* Method ID {assign.MethodId}: {cls.FullName}.{method.Name}{method.Signature} */");
        writer.WriteLine($"/* Bank {assign.Bank}, offset 0x{assign.OffsetInBank:X4} */");
        writer.WriteLine($"#pragma codeseg(push, \"BANK{assign.Bank:D2}\")");
        writer.WriteLine($"{returnType} {funcName}(void)");
        writer.WriteLine("{");

        if (method.Code != null && method.Code.Length > 0)
        {
            // Declare eval stack temp variables
            int maxTemps = Math.Max(method.MaxStack * 2, 4);
            for (int i = 0; i < maxTemps; i++)
            {
                writer.WriteLine($"    {CC65TypeMapper.StackType} s{i} = 0;");
            }

            // Declare locals
            for (int i = 0; i < method.MaxLocals; i++)
            {
                writer.WriteLine($"    {CC65TypeMapper.StackType} local_{i} = 0;");
            }

            writer.WriteLine();

            // Translate MSIL to C
            var iterator = new MsilIterator(method.Code, method);
            var stack = new CC65StackSimulator(method.MaxLocals, method.MaxStack * 2);
            var support = new CC65Support(
                iterator, method, stack, writer, _methodBank,
                ResolveMethodToken, TryResolveFrameworkMethod);

            while (iterator.MoveNext())
            {
                var opcode = iterator.CurrentOpcode;
                writer.WriteLine($"/* IL_{iterator.CurrentIndex:X4}: {opcode.Name} */");

                // TODO: Delegate to CC65OpcodeTranslator when opcode classes are implemented
            }
        }
        else
        {
            writer.WriteLine($"    /* TODO: No MSIL body for {method.Name} */");
        }

        if (returnType != "void")
            writer.WriteLine("    return 0;");

        writer.WriteLine("}");
        writer.WriteLine("#pragma codeseg(pop)");
    }

    // --- Fixed bank: kernel/dispatcher ---

    private void WriteKernelFile(StreamWriter writer)
    {
        writer.WriteLine("/* kernel.c — Fixed bank (last bank) */");
        writer.WriteLine("/* Atari XEGS Cartridge — Generated by JumpCS CC65 Backend */");
        writer.WriteLine();
        writer.WriteLine("/*");
        writer.WriteLine(" * Memory Map:");
        writer.WriteLine(" * $0000-$00FF  Zero Page (cc65 runtime + app vars)");
        writer.WriteLine(" * $0100-$01FF  6502 Hardware Stack");
        writer.WriteLine(" * $0200-$1FFF  Atari reserved (DOS)");
        writer.WriteLine(" * $2000-$5FFF  Free RAM (globals, heap, software stack)");
        writer.WriteLine(" * $6000-$7FFF  Atari reserved (display list, screen memory)");
        writer.WriteLine(" * $8000-$9FFF  Switchable ROM bank (generated code)");
        writer.WriteLine(" * $A000-$BFFF  Fixed ROM bank (this file)");
        writer.WriteLine(" * $C000-$FFFF  Atari OS and H/W chips");
        writer.WriteLine(" */");
        writer.WriteLine();
        writer.WriteLine("#include <atari.h>");
        writer.WriteLine("#include <stdint.h>");
        writer.WriteLine("#include \"methods.h\"");
        writer.WriteLine();
        writer.WriteLine("/* Bank switch register */");
        writer.WriteLine("#define BANK_SELECT (*(volatile uint8_t*)0xD500)");
        writer.WriteLine();
        writer.WriteLine("/* Bank call stack for nested cross-bank calls */");
        writer.WriteLine("#define BANK_STACK_SIZE 16");
        writer.WriteLine("static uint8_t bank_stack[BANK_STACK_SIZE];");
        writer.WriteLine("static uint8_t bank_sp = 0;");
        writer.WriteLine("static uint8_t current_bank = 0;");
        writer.WriteLine();

        // Bank switch routines
        writer.WriteLine("void __fastcall__ switch_bank(uint8_t bank)");
        writer.WriteLine("{");
        writer.WriteLine("    current_bank = bank;");
        writer.WriteLine("    BANK_SELECT = bank;");
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("int32_t __fastcall__ call_banked(uint8_t method_id)");
        writer.WriteLine("{");
        writer.WriteLine("    int32_t result;");
        writer.WriteLine("    uint8_t target_bank = method_bank_table[method_id];");
        writer.WriteLine("    bank_stack[bank_sp++] = current_bank;");
        writer.WriteLine("    switch_bank(target_bank);");
        writer.WriteLine("    result = method_func_table[method_id]();");
        writer.WriteLine("    switch_bank(bank_stack[--bank_sp]);");
        writer.WriteLine("    return result;");
        writer.WriteLine("}");
        writer.WriteLine();

        // Method tables
        writer.WriteLine("/* Bank assignment table */");
        writer.WriteLine("const uint8_t method_bank_table[NUM_METHODS] = {");
        foreach (var (key, assign) in _methodBank.Assignments.OrderBy(a => a.Value.MethodId))
        {
            writer.WriteLine($"    {assign.Bank},  /* {assign.MethodId}: {key} */");
        }
        writer.WriteLine("};");
        writer.WriteLine();

        writer.WriteLine("/* Function pointer table */");
        writer.WriteLine($"{CC65TypeMapper.StackType} (* const method_func_table[NUM_METHODS])(void) = {{");
        foreach (var cls in ClassMetadata.AllClasses.Where(c => c.IsNeeded))
        {
            foreach (var method in cls.Methods.Where(m => m.IsNeeded))
            {
                string key = CC65MethodBank.GetMethodKey(cls, method);
                if (_methodBank.Assignments.TryGetValue(key, out var assign))
                {
                    string funcName = GetCFunctionName(cls, method);
                    writer.WriteLine($"    ({CC65TypeMapper.StackType} (*)(void)){funcName},  /* {assign.MethodId} */");
                }
            }
        }
        writer.WriteLine("};");
        writer.WriteLine();

        // Entry point
        writer.WriteLine("/* Entry point */");
        writer.WriteLine("void main(void)");
        writer.WriteLine("{");
        writer.WriteLine("    /* Initialize bank 0 */");
        writer.WriteLine("    switch_bank(0);");
        writer.WriteLine();

        var mainMethod = ClassMetadata.AllClasses
            .Where(c => c.IsNeeded)
            .SelectMany(c => c.Methods)
            .FirstOrDefault(m => m.Name == "Main" && m.IsNeeded);

        if (mainMethod != null)
        {
            string key = CC65MethodBank.GetMethodKey(mainMethod.OwningClass, mainMethod);
            if (_methodBank.Assignments.TryGetValue(key, out var assign))
            {
                writer.WriteLine($"    call_banked({assign.MethodId}); /* {mainMethod.OwningClass.FullName}.Main */");
            }
        }
        else
        {
            writer.WriteLine("    /* WARNING: No Main method found */");
        }

        writer.WriteLine();
        writer.WriteLine("    /* Halt */");
        writer.WriteLine("    for(;;);");
        writer.WriteLine("}");
    }

    // --- Shared header ---

    private void WriteMethodsHeader(StreamWriter writer)
    {
        writer.WriteLine("/* methods.h — Generated by JumpCS CC65 Backend */");
        writer.WriteLine("#ifndef METHODS_H");
        writer.WriteLine("#define METHODS_H");
        writer.WriteLine();
        writer.WriteLine("#include <stdint.h>");
        writer.WriteLine();
        writer.WriteLine($"#define NUM_METHODS {_methodBank.Assignments.Count}");
        writer.WriteLine($"#define NUM_BANKS_USED {_methodBank.BanksUsed}");
        writer.WriteLine($"#define NUM_BANKS_TOTAL {CC65CartModel.TotalBanks(_model)}");
        writer.WriteLine();

        // Method ID defines
        writer.WriteLine("/* Method IDs */");
        foreach (var (key, assign) in _methodBank.Assignments.OrderBy(a => a.Value.MethodId))
        {
            string safeName = SanitizeIdentifier(key);
            writer.WriteLine($"#define MID_{safeName} {assign.MethodId}");
        }
        writer.WriteLine();

        // Function declarations
        writer.WriteLine("/* Method declarations */");
        foreach (var cls in ClassMetadata.AllClasses.Where(c => c.IsNeeded))
        {
            foreach (var method in cls.Methods.Where(m => m.IsNeeded))
            {
                string funcName = GetCFunctionName(cls, method);
                string returnType = CC65TypeMapper.ReturnTypeFromSignature(method.Signature);
                writer.WriteLine($"extern {returnType} {funcName}(void);");
            }
        }
        writer.WriteLine();

        // Dispatch declarations
        writer.WriteLine("/* Dispatch tables (defined in kernel.c) */");
        writer.WriteLine("extern const uint8_t method_bank_table[];");
        writer.WriteLine($"extern {CC65TypeMapper.StackType} (* const method_func_table[])(void);");
        writer.WriteLine();
        writer.WriteLine("/* Bank switching (defined in kernel.c) */");
        writer.WriteLine("void __fastcall__ switch_bank(uint8_t bank);");
        writer.WriteLine($"{CC65TypeMapper.StackType} __fastcall__ call_banked(uint8_t method_id);");
        writer.WriteLine();
        writer.WriteLine("#endif /* METHODS_H */");
    }

    // --- Linker config ---

    private void WriteLinkerConfig(StreamWriter writer)
    {
        int totalBanks = CC65CartModel.TotalBanks(_model);

        writer.WriteLine($"# xegs.cfg — Atari XEGS {CC65CartModel.ModelName(_model)} linker config");
        writer.WriteLine("# Generated by JumpCS CC65 Backend");
        writer.WriteLine();
        writer.WriteLine("SYMBOLS {");
        writer.WriteLine("    __STACKSIZE__: type = weak, value = $0800;");
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("MEMORY {");
        writer.WriteLine("    ZP:      start = $0082, size = $007E, type = rw, define = yes;");
        writer.WriteLine("    RAM:     start = $2000, size = $4000, type = rw, define = yes;  # $2000-$5FFF");

        for (int bank = 0; bank < totalBanks - 1; bank++)
        {
            writer.WriteLine($"    BANK{bank:D2}:  start = $8000, size = $2000, type = ro, file = \"%O\", fill = yes, fillval = $FF;");
        }

        writer.WriteLine($"    FIXED:  start = $A000, size = $2000, type = ro, file = \"%O\", fill = yes, fillval = $FF;  # Fixed bank");
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("SEGMENTS {");
        writer.WriteLine("    ZEROPAGE: load = ZP,    type = zp;");
        writer.WriteLine("    BSS:      load = RAM,   type = bss, define = yes;");
        writer.WriteLine("    DATA:     load = FIXED, type = rw,  run = RAM, define = yes;");
        writer.WriteLine("    STARTUP:  load = FIXED, type = ro;");
        writer.WriteLine("    CODE:     load = FIXED, type = ro;");
        writer.WriteLine("    RODATA:   load = FIXED, type = ro;");

        for (int bank = 0; bank < totalBanks - 1; bank++)
        {
            writer.WriteLine($"    BANK{bank:D2}:   load = BANK{bank:D2}, type = ro;");
        }

        writer.WriteLine("}");
    }

    // --- Makefile ---

    private void WriteMakefile(StreamWriter writer)
    {
        string targetName = Path.GetFileName(OutputBaseName);

        writer.WriteLine("# Makefile — Generated by JumpCS CC65 Backend");
        writer.WriteLine($"# Target: Atari XEGS {CC65CartModel.ModelName(_model)}");
        writer.WriteLine();
        writer.WriteLine("CC = cl65");
        writer.WriteLine("CFLAGS = -t atari -O --standard c99");
        writer.WriteLine("LDFLAGS = -C xegs.cfg");
        writer.WriteLine($"TARGET = {targetName}.xex");
        writer.WriteLine();

        var sources = new List<string> { "kernel.c" };
        for (int bank = 0; bank < _methodBank.BanksUsed; bank++)
        {
            sources.Add($"bank_{bank:D2}.c");
        }

        writer.WriteLine($"SOURCES = {string.Join(" \\\n          ", sources)}");
        writer.WriteLine("OBJECTS = $(SOURCES:.c=.o)");
        writer.WriteLine();
        writer.WriteLine(".PHONY: all clean");
        writer.WriteLine();
        writer.WriteLine("all: $(TARGET)");
        writer.WriteLine();
        writer.WriteLine("$(TARGET): $(OBJECTS)");
        writer.WriteLine("\t$(CC) $(LDFLAGS) -o $@ $^");
        writer.WriteLine();
        writer.WriteLine("%.o: %.c methods.h");
        writer.WriteLine("\t$(CC) $(CFLAGS) -c -o $@ $<");
        writer.WriteLine();
        writer.WriteLine("clean:");
        writer.WriteLine("\trm -f $(OBJECTS) $(TARGET)");
    }

    // --- Reporting ---

    public override void Report()
    {
        base.Report();
        Console.WriteLine($"  Target: Atari XEGS Cartridge");
        Console.WriteLine($"  Cart model: {CC65CartModel.ModelName(_model)}");
        Console.WriteLine($"  Banks used: {_methodBank.BanksUsed}/{CC65CartModel.SwitchableBanks(_model)} switchable + 1 fixed");
        Console.WriteLine($"  Methods: {_methodBank.Assignments.Count}");
        Console.WriteLine($"  Free RAM: $2000-$5FFF ({CC65MethodBank.RamSize / 1024}KB)");
    }

    // --- Helpers ---

    internal static string GetCFunctionName(ClassMetadata cls, MethodMetadata method)
    {
        string className = SanitizeIdentifier(cls.FullName);
        string methodName = SanitizeIdentifier(method.Name);
        return $"{className}_{methodName}";
    }

    private static string SanitizeIdentifier(string name)
    {
        return name
            .Replace(".", "_")
            .Replace("<", "_")
            .Replace(">", "_")
            .Replace("(", "_")
            .Replace(")", "_")
            .Replace(",", "_")
            .Replace(" ", "_");
    }
}